version: 2.1

orbs:
  node: cloudify/public-unittest-orb@volatile
  wagonorb: cloudify/wagon-bulder-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  managerorb: cloudify/manager-orb@volatile

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py36:
    environment:
      PYENV_VERSION: 3.6.5
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
      image: ubuntu-2004:202201-02

commands:

  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key -s aws_region_name=eu-central-2 --yum-package python-netaddr --yum-package git -p $(find ~/project/workspace/build/ -name *centos-Core*x86_64.wgn)  ~/project/plugin.yaml
      - run: ecosystem-test upload-plugin -PN terraform

  run_tf_vm_test:
    steps:
      - run: ecosystem-test local-blueprint-test -b examples/tg_blueprint.yaml --test-id=tg --on-failure=uninstall-force --timeout=1800 --required-ips 2

jobs:
  integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_tf_vm_test

workflows:
  version: 2.1
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_documentation_job
      - node/validate_version_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
      - integration_tests_py3:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
          requires:
            - wagonorb/build_bundle
      - releaseorb/release:
          filters:
            branches:
              only: /main/
          requires:
            - wagonorb/build_bundle
            - node/unittests_job
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
            - integration_tests_py3
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /main/
          requires:
            - releaseorb/release
            - node/validate_documentation_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,2,4,6"
        filters:
          branches:
            only:
              - main
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /main/
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
      - integration_tests_py3:
          requires:
            - wagonorb/build_bundle
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
