version: 2.1

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  node: cloudify/public-unittest-orb@volatile
  wagonorb: cloudify/wagon-bulder-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  managerorb: cloudify/manager-orb@volatile
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py36:
    environment:
      PYENV_VERSION: 3.6.5
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
      image: ubuntu-2004:202201-02

commands:

  setup_manager:
    steps:
      - run: |
          if [[ -z "${CLOUDIFY_HOST}" ]]; then
              exit 1
          fi
      - run: |
          if [[ -z "${CLOUDIFY_TENANT}" ]]; then
              exit 1
          fi
      - run: |
          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
              exit 1
          fi
      - run: |
          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
          if [[ $response != 200 ]]; then
              echo "Failed to get manager status";
              exit 1
          fi
      - run: pip3 install urllib3==1.26.15 requests-toolbelt==0.10.1
      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
      - run: git submodule update --init --recursive --remote

  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-remote-test-manager -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key -s aws_region_name=eu-west-1 -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml
      - run: ecosystem-test remote-upload-plugin -PN terraform -WT manylinux

  run_tf_vm_test:
    steps:
      - run: ecosystem-test remote-blueprint-test -b examples/tg_blueprint.yaml --test-id=tg-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=1800 --required-ips 2 | tee -a run_tf_vm_test.log
      - store_artifacts:
          path: run_tf_vm_test.log
      - slack/notify_failed

jobs:
  integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - setup_manager
      - prepare_test_manager
      - run_tf_vm_test

workflows:
  version: 2.1
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
      - node/validate_documentation_job
      - node/validate_version_job
     
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
      - releaseorb/release:
          filters:
            branches:
              only: /main/
          requires:
            - node/unittests_job
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
            - integration_tests_py3
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /main/
          requires:
            - releaseorb/release
            - node/validate_documentation_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,2,4,6"
        filters:
          branches:
            only:
              - main
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
      - integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|main|dev)/
